import Head from 'next/head'
import React, { useEffect } from 'react'

function Layout({ title, children }) {
    useEffect(() => {
        document.body.style.backgroundColor = '#cbd5e1';
    }, [])
    return (
        <div className="bg-slate-300">
            <Head>
                <title>{title} | Fath Pokedex</title>
                {/* <meta name="description" content="Generated by create next app" /> */}
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='mx-auto'>
                {children}
            </main>
        </div>
    )
}

export default Layout